### ISSUE TITLE
review if(memorySecure) build an encrypted DB, it should be if(!memorySecure) 

### ISSUE THREAD

**Issue by AnwarBaniAmer** [sonique6784/SQLCipherPerformance#1]
`fun getInstance(
            context: Context,
            secure: Boolean = false,
            memorySecure: Boolean = false
        ): AppDatabase {
            return if (secure) {
                **if(memorySecure) {**
                    personDBSecure ?: synchronized(this) {
                        **personDBSecure** ?: buildDatabase(context, secure, memorySecure).also { personDBSecure = it }
                    }
                } else {
                    **personDBSecureWithMemorySecurity** ?: synchronized(this) {
                        personDBSecureWithMemorySecurity ?: buildDatabase(context, secure, memorySecure).also { personDBSecureWithMemorySecurity = it }
                    }
                }
            } else {
                personDB ?: synchronized(this) {
                    personDB ?: buildDatabase(context, secure).also { personDB = it }
                }
            }
        }`

**Comment by sonique6784** [comment]
thanks, this is fixed
